# -*- coding: utf-8 -*-
"""
List all nations in the world with ISO codes.
"""


def all(digits=3):
    """
    Return a tuple of django model choices of all nations.
    """
    if digits == 3:
        return NATIONS_3
    if digits == 2:
        return NATIONS_2

NATIONS_2 = (
    # More likely nations first
    (u"LT", u"Lithuania",),
    (u"LV", u"Latvia",),
    (u"EE", u"Estonia",),
    (u"BY", u"Belarus",),
    (u"RU", u"Russian Federation",),
    (u"NO", u"Norway",),
    (u"FI", u"Finland",),
    (u"DK", u"Denmark",),
    (u"SE", u"Sweden",),
    (u"PL", u"Poland",),
    (u"DE", u"Germany",),
    (u"PS", u"Palestine, State of",),
    # Alphabetical order from here.
    (u"AF", u"Afghanistan",),
    (u"AL", u"Albania",),
    (u"DZ", u"Algeria",),
    (u"AS", u"American Samoa",),
    (u"AD", u"Andorra",),
    (u"AO", u"Angola",),
    (u"AI", u"Anguilla",),
    (u"AQ", u"Antarctica",),
    (u"AG", u"Antigua and Barbuda",),
    (u"AR", u"Argentina",),
    (u"AM", u"Armenia",),
    (u"AW", u"Aruba",),
    (u"AU", u"Australia",),
    (u"AT", u"Austria",),
    (u"AZ", u"Azerbaijan",),
    (u"BS", u"Bahamas",),
    (u"BH", u"Bahrain",),
    (u"BD", u"Bangladesh",),
    (u"BB", u"Barbados",),
    (u"BE", u"Belgium",),
    (u"BZ", u"Belize",),
    (u"BJ", u"Benin",),
    (u"BM", u"Bermuda",),
    (u"BT", u"Bhutan",),
    (u"BO", u"Bolivia, Plurinational State of",),
    (u"BQ", u"Bonaire, Sint Eustatius and Saba",),
    (u"BA", u"Bosnia and Herzegovina",),
    (u"BW", u"Botswana",),
    (u"BV", u"Bouvet Island",),
    (u"BR", u"Brazil",),
    (u"IO", u"British Indian Ocean Territory",),
    (u"BN", u"Brunei Darussalam",),
    (u"BG", u"Bulgaria",),
    (u"BF", u"Burkina Faso",),
    (u"BI", u"Burundi",),
    (u"CV", u"Cabo Verde",),
    (u"KH", u"Cambodia",),
    (u"CM", u"Cameroon",),
    (u"CA", u"Canada",),
    (u"KY", u"Cayman Islands",),
    (u"CF", u"Central African Republic",),
    (u"TD", u"Chad",),
    (u"CL", u"Chile",),
    (u"CN", u"China",),
    (u"CX", u"Christmas Island",),
    (u"CC", u"Cocos (Keeling) Islands",),
    (u"CO", u"Colombia",),
    (u"KM", u"Comoros",),
    (u"CG", u"Congo",),
    (u"CD", u"Congo, the Democratic Republic of the",),
    (u"CK", u"Cook Islands",),
    (u"CR", u"Costa Rica",),
    (u"HR", u"Croatia",),
    (u"CU", u"Cuba",),
    (u"CW", u"Curaçao",),
    (u"CY", u"Cyprus",),
    (u"CZ", u"Czech Republic",),
    (u"CI", u"Côte d'Ivoire",),
    (u"DJ", u"Djibouti",),
    (u"DM", u"Dominica",),
    (u"DO", u"Dominican Republic",),
    (u"EC", u"Ecuador",),
    (u"EG", u"Egypt",),
    (u"SV", u"El Salvador",),
    (u"GQ", u"Equatorial Guinea",),
    (u"ER", u"Eritrea",),
    (u"ET", u"Ethiopia",),
    (u"FK", u"Falkland Islands (Malvinas)",),
    (u"FO", u"Faroe Islands",),
    (u"FJ", u"Fiji",),
    (u"FR", u"France",),
    (u"GF", u"French Guiana",),
    (u"PF", u"French Polynesia",),
    (u"TF", u"French Southern Territories",),
    (u"GA", u"Gabon",),
    (u"GM", u"Gambia",),
    (u"GE", u"Georgia",),
    (u"GH", u"Ghana",),
    (u"GI", u"Gibraltar",),
    (u"GR", u"Greece",),
    (u"GL", u"Greenland",),
    (u"GD", u"Grenada",),
    (u"GP", u"Guadeloupe",),
    (u"GU", u"Guam",),
    (u"GT", u"Guatemala",),
    (u"GG", u"Guernsey",),
    (u"GN", u"Guinea",),
    (u"GW", u"Guinea-Bissau",),
    (u"GY", u"Guyana",),
    (u"HT", u"Haiti",),
    (u"HM", u"Heard Island and McDonald Islands",),
    (u"VA", u"Holy See (Vatican City State)",),
    (u"HN", u"Honduras",),
    (u"HK", u"Hong Kong",),
    (u"HU", u"Hungary",),
    (u"IS", u"Iceland",),
    (u"IN", u"India",),
    (u"ID", u"Indonesia",),
    (u"IR", u"Iran, Islamic Republic of",),
    (u"IQ", u"Iraq",),
    (u"IE", u"Ireland",),
    (u"IM", u"Isle of Man",),
    (u"IL", u"Israel",),
    (u"IT", u"Italy",),
    (u"JM", u"Jamaica",),
    (u"JP", u"Japan",),
    (u"JE", u"Jersey",),
    (u"JO", u"Jordan",),
    (u"KZ", u"Kazakhstan",),
    (u"KE", u"Kenya",),
    (u"KI", u"Kiribati",),
    (u"KP", u"Korea, Democratic People's Republic of",),
    (u"KR", u"Korea, Republic of",),
    (u"KW", u"Kuwait",),
    (u"KG", u"Kyrgyzstan",),
    (u"LA", u"Lao People's Democratic Republic",),
    (u"LB", u"Lebanon",),
    (u"LS", u"Lesotho",),
    (u"LR", u"Liberia",),
    (u"LY", u"Libya",),
    (u"LI", u"Liechtenstein",),
    (u"LU", u"Luxembourg",),
    (u"MO", u"Macao",),
    (u"MK", u"Macedonia, the former Yugoslav Republic of",),
    (u"MG", u"Madagascar",),
    (u"MW", u"Malawi",),
    (u"MY", u"Malaysia",),
    (u"MV", u"Maldives",),
    (u"ML", u"Mali",),
    (u"MT", u"Malta",),
    (u"MH", u"Marshall Islands",),
    (u"MQ", u"Martinique",),
    (u"MR", u"Mauritania",),
    (u"MU", u"Mauritius",),
    (u"YT", u"Mayotte",),
    (u"MX", u"Mexico",),
    (u"FM", u"Micronesia, Federated States of",),
    (u"MD", u"Moldova, Republic of",),
    (u"MC", u"Monaco",),
    (u"MN", u"Mongolia",),
    (u"ME", u"Montenegro",),
    (u"MS", u"Montserrat",),
    (u"MA", u"Morocco",),
    (u"MZ", u"Mozambique",),
    (u"MM", u"Myanmar",),
    (u"NA", u"Namibia",),
    (u"NR", u"Nauru",),
    (u"NP", u"Nepal",),
    (u"NL", u"Netherlands",),
    (u"NC", u"New Caledonia",),
    (u"NZ", u"New Zealand",),
    (u"NI", u"Nicaragua",),
    (u"NE", u"Niger",),
    (u"NG", u"Nigeria",),
    (u"NU", u"Niue",),
    (u"NF", u"Norfolk Island",),
    (u"MP", u"Northern Mariana Islands",),
    (u"OM", u"Oman",),
    (u"PK", u"Pakistan",),
    (u"PW", u"Palau",),
    (u"PA", u"Panama",),
    (u"PG", u"Papua New Guinea",),
    (u"PY", u"Paraguay",),
    (u"PE", u"Peru",),
    (u"PH", u"Philippines",),
    (u"PN", u"Pitcairn",),
    (u"PT", u"Portugal",),
    (u"PR", u"Puerto Rico",),
    (u"QA", u"Qatar",),
    (u"RO", u"Romania",),
    (u"RW", u"Rwanda",),
    (u"RE", u"Réunion",),
    (u"BL", u"Saint Barthélemy",),
    (u"SH", u"Saint Helena, Ascension and Tristan da Cunha",),
    (u"KN", u"Saint Kitts and Nevis",),
    (u"LC", u"Saint Lucia",),
    (u"MF", u"Saint Martin (French part)",),
    (u"PM", u"Saint Pierre and Miquelon",),
    (u"VC", u"Saint Vincent and the Grenadines",),
    (u"WS", u"Samoa",),
    (u"SM", u"San Marino",),
    (u"ST", u"Sao Tome and Principe",),
    (u"SA", u"Saudi Arabia",),
    (u"SN", u"Senegal",),
    (u"RS", u"Serbia",),
    (u"SC", u"Seychelles",),
    (u"SL", u"Sierra Leone",),
    (u"SG", u"Singapore",),
    (u"SX", u"Sint Maarten (Dutch part)",),
    (u"SK", u"Slovakia",),
    (u"SI", u"Slovenia",),
    (u"SB", u"Solomon Islands",),
    (u"SO", u"Somalia",),
    (u"ZA", u"South Africa",),
    (u"GS", u"South Georgia and the South Sandwich Islands",),
    (u"SS", u"South Sudan",),
    (u"ES", u"Spain",),
    (u"LK", u"Sri Lanka",),
    (u"SD", u"Sudan",),
    (u"SR", u"Suriname",),
    (u"SJ", u"Svalbard and Jan Mayen",),
    (u"SZ", u"Swaziland",),
    (u"CH", u"Switzerland",),
    (u"SY", u"Syrian Arab Republic",),
    (u"TW", u"Taiwan, Province of China",),
    (u"TJ", u"Tajikistan",),
    (u"TZ", u"Tanzania, United Republic of",),
    (u"TH", u"Thailand",),
    (u"TL", u"Timor-Leste",),
    (u"TG", u"Togo",),
    (u"TK", u"Tokelau",),
    (u"TO", u"Tonga",),
    (u"TT", u"Trinidad and Tobago",),
    (u"TN", u"Tunisia",),
    (u"TR", u"Turkey",),
    (u"TM", u"Turkmenistan",),
    (u"TC", u"Turks and Caicos Islands",),
    (u"TV", u"Tuvalu",),
    (u"UG", u"Uganda",),
    (u"UA", u"Ukraine",),
    (u"AE", u"United Arab Emirates",),
    (u"GB", u"United Kingdom",),
    (u"UM", u"United States Minor Outlying Islands",),
    (u"US", u"United States",),
    (u"UY", u"Uruguay",),
    (u"UZ", u"Uzbekistan",),
    (u"VU", u"Vanuatu",),
    (u"VE", u"Venezuela, Bolivarian Republic of",),
    (u"VN", u"Viet Nam",),
    (u"VG", u"Virgin Islands, British",),
    (u"VI", u"Virgin Islands, U.S.",),
    (u"WF", u"Wallis and Futuna",),
    (u"EH", u"Western Sahara",),
    (u"YE", u"Yemen",),
    (u"ZM", u"Zambia",),
    (u"ZW", u"Zimbabwe",),
    (u"AX", u"Åland Islands",),
)

NATIONS_3 = (
    (u"ABW", u"Aruba",),
    (u"AFG", u"Afghanistan",),
    (u"AGO", u"Angola",),
    (u"AIA", u"Anguilla",),
    (u"ALA", u"Åland Islands",),
    (u"ALB", u"Albania",),
    (u"AND", u"Andorra",),
    (u"ARE", u"United Arab Emirates",),
    (u"ARG", u"Argentina",),
    (u"ARM", u"Armenia",),
    (u"ASM", u"American Samoa",),
    (u"ATA", u"Antarctica",),
    (u"ATF", u"French Southern Territories",),
    (u"ATG", u"Antigua and Barbuda",),
    (u"AUS", u"Australia",),
    (u"AUT", u"Austria",),
    (u"AZE", u"Azerbaijan",),
    (u"BDI", u"Burundi",),
    (u"BEL", u"Belgium",),
    (u"BEN", u"Benin",),
    (u"BES", u"Bonaire, Sint Eustatius and Saba",),
    (u"BFA", u"Burkina Faso",),
    (u"BGD", u"Bangladesh",),
    (u"BGR", u"Bulgaria",),
    (u"BHR", u"Bahrain",),
    (u"BHS", u"Bahamas",),
    (u"BIH", u"Bosnia and Herzegovina",),
    (u"BLM", u"Saint Barthélemy",),
    (u"BLR", u"Belarus",),
    (u"BLZ", u"Belize",),
    (u"BMU", u"Bermuda",),
    (u"BOL", u"Bolivia, Plurinational State of",),
    (u"BRA", u"Brazil",),
    (u"BRB", u"Barbados",),
    (u"BRN", u"Brunei Darussalam",),
    (u"BTN", u"Bhutan",),
    (u"BVT", u"Bouvet Island",),
    (u"BWA", u"Botswana",),
    (u"CAF", u"Central African Republic",),
    (u"CAN", u"Canada",),
    (u"CCK", u"Cocos (Keeling) Islands",),
    (u"CHE", u"Switzerland",),
    (u"CHL", u"Chile",),
    (u"CHN", u"China",),
    (u"CIV", u"Côte d'Ivoire",),
    (u"CMR", u"Cameroon",),
    (u"COD", u"Congo, the Democratic Republic of the",),
    (u"COG", u"Congo",),
    (u"COK", u"Cook Islands",),
    (u"COL", u"Colombia",),
    (u"COM", u"Comoros",),
    (u"CPV", u"Cape Verde",),
    (u"CRI", u"Costa Rica",),
    (u"CUB", u"Cuba",),
    (u"CUW", u"Curaçao",),
    (u"CXR", u"Christmas Island",),
    (u"CYM", u"Cayman Islands",),
    (u"CYP", u"Cyprus",),
    (u"CZE", u"Czech Republic",),
    (u"DEU", u"Germany",),
    (u"DJI", u"Djibouti",),
    (u"DMA", u"Dominica",),
    (u"DNK", u"Denmark",),
    (u"DOM", u"Dominican Republic",),
    (u"DZA", u"Algeria",),
    (u"ECU", u"Ecuador",),
    (u"EGY", u"Egypt",),
    (u"ERI", u"Eritrea",),
    (u"ESH", u"Western Sahara",),
    (u"ESP", u"Spain",),
    (u"EST", u"Estonia",),
    (u"ETH", u"Ethiopia",),
    (u"FIN", u"Finland",),
    (u"FJI", u"Fiji",),
    (u"FLK", u"Falkland Islands (Malvinas)",),
    (u"FRA", u"France",),
    (u"FRO", u"Faroe Islands",),
    (u"FSM", u"Micronesia, Federated States of",),
    (u"GAB", u"Gabon",),
    (u"GBR", u"United Kingdom",),
    (u"GEO", u"Georgia",),
    (u"GGY", u"Guernsey",),
    (u"GHA", u"Ghana",),
    (u"GIB", u"Gibraltar",),
    (u"GIN", u"Guinea",),
    (u"GLP", u"Guadeloupe",),
    (u"GMB", u"Gambia",),
    (u"GNB", u"Guinea-Bissau",),
    (u"GNQ", u"Equatorial Guinea",),
    (u"GRC", u"Greece",),
    (u"GRD", u"Grenada",),
    (u"GRL", u"Greenland",),
    (u"GTM", u"Guatemala",),
    (u"GUF", u"French Guiana",),
    (u"GUM", u"Guam",),
    (u"GUY", u"Guyana",),
    (u"HKG", u"Hong Kong",),
    (u"HMD", u"Heard Island and McDonald Islands",),
    (u"HND", u"Honduras",),
    (u"HRV", u"Croatia",),
    (u"HTI", u"Haiti",),
    (u"HUN", u"Hungary",),
    (u"IDN", u"Indonesia",),
    (u"IMN", u"Isle of Man",),
    (u"IND", u"India",),
    (u"IOT", u"British Indian Ocean Territory",),
    (u"IRL", u"Ireland",),
    (u"IRN", u"Iran, Islamic Republic of",),
    (u"IRQ", u"Iraq",),
    (u"ISL", u"Iceland",),
    (u"ISR", u"Israel",),
    (u"ITA", u"Italy",),
    (u"JAM", u"Jamaica",),
    (u"JEY", u"Jersey",),
    (u"JOR", u"Jordan",),
    (u"JPN", u"Japan",),
    (u"KAZ", u"Kazakhstan",),
    (u"KEN", u"Kenya",),
    (u"KGZ", u"Kyrgyzstan",),
    (u"KHM", u"Cambodia",),
    (u"KIR", u"Kiribati",),
    (u"KNA", u"Saint Kitts and Nevis",),
    (u"KOR", u"Korea, Republic of",),
    (u"KWT", u"Kuwait",),
    (u"LAO", u"Lao People's Democratic Republic",),
    (u"LBN", u"Lebanon",),
    (u"LBR", u"Liberia",),
    (u"LBY", u"Libya",),
    (u"LCA", u"Saint Lucia",),
    (u"LIE", u"Liechtenstein",),
    (u"LKA", u"Sri Lanka",),
    (u"LSO", u"Lesotho",),
    (u"LTU", u"Lithuania",),
    (u"LUX", u"Luxembourg",),
    (u"LVA", u"Latvia",),
    (u"MAC", u"Macao",),
    (u"MAF", u"Saint Martin (French part)",),
    (u"MAR", u"Morocco",),
    (u"MCO", u"Monaco",),
    (u"MDA", u"Moldova, Republic of",),
    (u"MDG", u"Madagascar",),
    (u"MDV", u"Maldives",),
    (u"MEX", u"Mexico",),
    (u"MHL", u"Marshall Islands",),
    (u"MKD", u"Macedonia, the former Yugoslav Republic of",),
    (u"MLI", u"Mali",),
    (u"MLT", u"Malta",),
    (u"MMR", u"Myanmar",),
    (u"MNE", u"Montenegro",),
    (u"MNG", u"Mongolia",),
    (u"MNP", u"Northern Mariana Islands",),
    (u"MOZ", u"Mozambique",),
    (u"MRT", u"Mauritania",),
    (u"MSR", u"Montserrat",),
    (u"MTQ", u"Martinique",),
    (u"MUS", u"Mauritius",),
    (u"MWI", u"Malawi",),
    (u"MYS", u"Malaysia",),
    (u"MYT", u"Mayotte",),
    (u"NAM", u"Namibia",),
    (u"NCL", u"New Caledonia",),
    (u"NER", u"Niger",),
    (u"NFK", u"Norfolk Island",),
    (u"NGA", u"Nigeria",),
    (u"NIC", u"Nicaragua",),
    (u"NIU", u"Niue",),
    (u"NLD", u"Netherlands",),
    (u"NOR", u"Norway",),
    (u"NPL", u"Nepal",),
    (u"NRU", u"Nauru",),
    (u"NZL", u"New Zealand",),
    (u"OMN", u"Oman",),
    (u"PAK", u"Pakistan",),
    (u"PAN", u"Panama",),
    (u"PCN", u"Pitcairn",),
    (u"PER", u"Peru",),
    (u"PHL", u"Philippines",),
    (u"PLW", u"Palau",),
    (u"PNG", u"Papua New Guinea",),
    (u"POL", u"Poland",),
    (u"PRI", u"Puerto Rico",),
    (u"PRK", u"Korea, Democratic People's Republic of",),
    (u"PRT", u"Portugal",),
    (u"PRY", u"Paraguay",),
    (u"PSE", u"Palestine, State of",),
    (u"PYF", u"French Polynesia",),
    (u"QAT", u"Qatar",),
    (u"REU", u"Réunion",),
    (u"ROU", u"Romania",),
    (u"RUS", u"Russian Federation",),
    (u"RWA", u"Rwanda",),
    (u"SAU", u"Saudi Arabia",),
    (u"SDN", u"Sudan",),
    (u"SEN", u"Senegal",),
    (u"SGP", u"Singapore",),
    (u"SGS", u"South Georgia and the South Sandwich Islands",),
    (u"SHN", u"Saint Helena, Ascension and Tristan da Cunha",),
    (u"SJM", u"Svalbard and Jan Mayen",),
    (u"SLB", u"Solomon Islands",),
    (u"SLE", u"Sierra Leone",),
    (u"SLV", u"El Salvador",),
    (u"SMR", u"San Marino",),
    (u"SOM", u"Somalia",),
    (u"SPM", u"Saint Pierre and Miquelon",),
    (u"SRB", u"Serbia",),
    (u"SSD", u"South Sudan",),
    (u"STP", u"Sao Tome and Principe",),
    (u"SUR", u"Suriname",),
    (u"SVK", u"Slovakia",),
    (u"SVN", u"Slovenia",),
    (u"SWE", u"Sweden",),
    (u"SWZ", u"Swaziland",),
    (u"SXM", u"Sint Maarten (Dutch part)",),
    (u"SYC", u"Seychelles",),
    (u"SYR", u"Syrian Arab Republic",),
    (u"TCA", u"Turks and Caicos Islands",),
    (u"TCD", u"Chad",),
    (u"TGO", u"Togo",),
    (u"THA", u"Thailand",),
    (u"TJK", u"Tajikistan",),
    (u"TKL", u"Tokelau",),
    (u"TKM", u"Turkmenistan",),
    (u"TLS", u"Timor-Leste",),
    (u"TON", u"Tonga",),
    (u"TTO", u"Trinidad and Tobago",),
    (u"TUN", u"Tunisia",),
    (u"TUR", u"Turkey",),
    (u"TUV", u"Tuvalu",),
    (u"TWN", u"Taiwan, Province of China",),
    (u"TZA", u"Tanzania, United Republic of",),
    (u"UGA", u"Uganda",),
    (u"UKR", u"Ukraine",),
    (u"UMI", u"United States Minor Outlying Islands",),
    (u"URY", u"Uruguay",),
    (u"USA", u"United States",),
    (u"UZB", u"Uzbekistan",),
    (u"VAT", u"Holy See (Vatican City State)",),
    (u"VCT", u"Saint Vincent and the Grenadines",),
    (u"VEN", u"Venezuela, Bolivarian Republic of",),
    (u"VGB", u"Virgin Islands, British",),
    (u"VIR", u"Virgin Islands, U.S.",),
    (u"VNM", u"Viet Nam",),
    (u"VUT", u"Vanuatu",),
    (u"WLF", u"Wallis and Futuna",),
    (u"WSM", u"Samoa",),
    (u"YEM", u"Yemen",),
    (u"ZAF", u"South Africa",),
    (u"ZMB", u"Zambia",),
    (u"ZWE", u"Zimbabwe",),
)
